DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;

CREATE TABLE users( --user table if I come back to the project and expand it with different users
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL
);  

CREATE TABLE books(
    book_id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year VARCHAR(4),
    cover_id INTEGER
);

CREATE TABLE reviews(
    review_id SERIAL PRIMARY KEY,
    date TEXT,
    review_text TEXT NOT NULL,
    rating INTEGER NOT NULL,
    review_title VARCHAR(100),
    book_id INTEGER REFERENCES books(book_id),
    user_id INTEGER REFERENCES users(user_id),
    review_update_date TEXT,
    UNIQUE(book_id, user_id)
);

INSERT INTO users(username)
VALUES('Default');

-- Insert books
INSERT INTO books (book_id, title, author, year, cover_id) VALUES
(1, 'The Final Empire', 'Brandon Sanderson', '2001', 14658160),
(2, 'Novels (Hobbit / Lord of the Rings)', 'J.R.R. Tolkien', '1979', 255844),
(3, 'The Song of Achilles', 'Madeline Miller', '2011', 7098465),
(4, 'A Bitter Tea', 'Unknown Author', '2025', NULL),
(5, 'The Ruins of Gorlan', 'John Flanagan', '2004', 6401507),
(6, 'Twilight', 'Stephenie Meyer', '2005', 12641977),
(7, 'Star Wars', 'Kieron Gillen', '2016', 12763741),
(8, 'The Book of Dragons', 'Edith Nesbit', '1973', 4342323),
(9, 'The Way of Kings', 'Brandon Sanderson', '2010', 14658316),
(10, 'Mister Monday (The Keys to the Kingdom, Book 1)', 'Garth Nix', '2003', 8349916),
(11, 'When Duty Calls', 'B. J. Daniels', '2003', 2408841),
(12, 'Modelland', 'Tyra Banks', '2011', 6906470),
(13, 'The unknown citizen', 'Tony Parker', '1963', NULL),
(14, 'Average Boy''s above-Average Summer', 'Bob Smiley', '2024', NULL),
(15, 'Eragon', 'Christopher Paolini', '2000', 13921600),
(16, 'The Blood of Olympus', 'Rick Riordan', '2001', 7303498),
(17, 'Foreign tax planning, 1981', 'Unknown Author', '1981', NULL),
(18, 'Hans Andersen''s Fairy Tales', 'Hans Christian Andersen', '1846', 320591),
(19, 'To Sleep in a Sea of Stars', 'Christopher Paolini', '2019', 10419780),
(20, 'Hell Divers II', 'Nicholas Sansbury Smith', '2017', 11386248);

-- Insert reviews
INSERT INTO reviews (review_id, date, review_text, rating, review_title, book_id, user_id, review_update_date) VALUES
(1, '2026-07-04T22:49:54.948Z', 'Nam aliquet tellus sapien, sed laoreet lectus faucibus a. Aenean mollis, sapien quis facilisis euismod, sapien dui mollis augue, ac condimentum mi tortor vel turpis. Donec at libero eu dui commodo tempor. Pellentesque lacus nunc, pulvinar a metus id, dapibus tristique augue. Nunc ante lorem, placerat quis fermentum ornare, auctor ac est. Vivamus consequat orci tortor, eu dignissim turpis eleifend sed. Duis pharetra risus vel urna varius vestibulum. Cras iaculis fermentum placerat. Proin felis libero, vestibulum vitae odio sed, interdum ullamcorper eros. Donec eget tempus nisl, ornare bibendum eros.', 4, 'Mistborn is amazing', 1, 1, '2026-07-05T08:48:00.383Z'),
(2, '2026-07-05T08:49:04.758Z', 'Sed sollicitudin faucibus gravida. Nam pharetra, arcu aliquet ultricies tincidunt, ante nibh lobortis nunc, ut dignissim magna purus non dolor. Pellentesque blandit rhoncus egestas. Praesent non pretium diam. Vivamus pulvinar molestie nisi, sollicitudin imperdiet tortor placerat eleifend. Quisque purus ipsum, bibendum in nibh vel, tempus eleifend mi. Vestibulum ac enim sodales, hendrerit elit a, euismod felis. Sed ultrices ullamcorper odio vel facilisis. Ut semper, nulla quis feugiat aliquet, purus nisl hendrerit eros, sit amet volutpat leo erat in sem. Cras leo nunc, sollicitudin non commodo non, tincidunt quis nunc. In sed mauris quis leo euismod posuere sed et arcu. Duis ultricies sit amet purus in fermentum. Donec finibus lectus quis elementum egestas. Vestibulum vitae laoreet eros. Etiam posuere justo a mi cursus, in eleifend lorem euismod. Nunc elit velit, tempus eu pretium nec, cursus eget velit.', 5, 'A book for the ages', 2, 1, '2026-07-05T08:49:09.941Z'),
(3, '2026-07-05T08:50:17.748Z', 'Mauris viverra ipsum lorem, in laoreet nisi imperdiet eu. Pellentesque ullamcorper convallis eros nec aliquam. Praesent at tincidunt augue. Ut ultricies dui lacus, ut suscipit arcu consequat a. Aliquam erat volutpat. Suspendisse egestas ex mattis, imperdiet eros in, gravida est. Quisque sed augue auctor, viverra ante at, placerat neque.
Phasellus hendrerit facilisis erat, sit amet pulvinar nisl luctus sed. Nulla est ex, vulputate et arcu fermentum, volutpat pharetra turpis. Curabitur lectus leo, consequat ac maximus a, semper sed ligula. Aliquam pharetra porttitor dui, vel faucibus est lacinia vitae. In lacinia erat a leo ornare viverra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo felis lorem, eu tincidunt turpis iaculis nec.', 4, 'Such a moving story', 3, 1, '2026-07-05T08:50:26.897Z'),
(4, '2026-07-05T08:52:46.033Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo neque sit amet purus porttitor, sed egestas sem malesuada. Sed semper iaculis ligula a laoreet. Nam vel faucibus leo. Etiam pharetra neque ut enim ornare, auctor congue augue bibendum. Cras vitae molestie orci. Cras suscipit mollis accumsan. Nullam id magna in purus fringilla imperdiet. Ut mi eros, aliquet vitae mauris a, ultrices volutpat leo.', 2, 'Not much to say about this', 4, 1, NULL),
(5, '2026-07-05T09:03:14.775Z', 'Fusce iaculis mauris at blandit condimentum. Maecenas eget est id lacus porttitor ullamcorper. Ut non elementum velit. Donec non blandit lorem, in egestas odio. Donec sit amet augue condimentum, volutpat velit nec, vulputate est. Vestibulum mollis metus urna, ut viverra elit hendrerit quis. Aenean bibendum tempus erat, eu iaculis nisl. Praesent orci ante, sagittis eu consectetur ut, tristique nec lacus. Proin vulputate viverra dapibus. Sed in varius diam. Maecenas venenatis arcu vitae sem faucibus, sed interdum quam venenatis. Pellentesque congue elit nec neque finibus, vitae pretium eros vulputate. Fusce sodales dictum tortor ac finibus. Quisque quis lacinia neque. Nulla sit amet eros augue. Cras quis egestas libero.
Nam ornare, magna ut suscipit accumsan, tortor turpis fringilla leo, non vehicula ante enim vel elit. Morbi ut felis lobortis, tincidunt arcu a, hendrerit nisi. Proin pharetra lorem tellus, id fermentum justo convallis et. Maecenas at eros at lacus aliquam varius eu vel neque. Proin mollis pulvinar tristique.', 5, 'Loved the story', 5, 1, NULL),
(6, '2026-07-05T09:04:11.383Z', 'Phasellus hendrerit facilisis erat, sit amet pulvinar nisl luctus sed. Nulla est ex, vulputate et arcu fermentum, volutpat pharetra turpis. Curabitur lectus leo, consequat ac maximus a, semper sed ligula. Aliquam pharetra porttitor dui, vel faucibus est lacinia vitae. In lacinia erat a leo ornare viverra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo felis lorem, eu tincidunt turpis iaculis nec.', 2, 'This is not for me', 6, 1, NULL),
(7, '2026-07-05T09:11:55.026Z', 'Vivamus quis eleifend orci. Praesent sed purus commodo, feugiat quam quis, lacinia nisi. Integer hendrerit ipsum vitae arcu gravida vestibulum.', 1, 'Had high hopes', 7, 1, NULL),
(8, '2026-07-05T09:14:28.949Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo neque sit amet purus porttitor, sed egestas sem malesuada. Sed semper iaculis ligula a laoreet. Nam vel faucibus leo. Etiam pharetra neque ut enim ornare, auctor congue augue bibendum. Cras vitae molestie orci. Cras suscipit mollis accumsan. Nullam id magna in purus fringilla imperdiet. Ut mi eros, aliquet vitae mauris a, ultrices volutpat leo.', 2, 'Dragons made it for me', 8, 1, NULL),
(9, '2026-07-05T09:15:13.241Z', 'Nam ornare, magna ut suscipit accumsan, tortor turpis fringilla leo, non vehicula ante enim vel elit. Morbi ut felis lobortis, tincidunt arcu a, hendrerit nisi. Proin pharetra lorem tellus, id fermentum justo convallis et. Maecenas at eros at lacus aliquam varius eu vel neque. Proin mollis pulvinar tristique. Vestibulum pulvinar convallis lorem sed porta. Nulla egestas, purus gravida bibendum feugiat, elit ex semper lorem, eu semper diam turpis id massa. Suspendisse non sem tempor, ornare ex sit amet, sollicitudin nulla. Proin magna metus, interdum vel dolor at, dictum lobortis est. Aliquam semper, nisl vitae rhoncus hendrerit, quam velit rutrum ante, vel malesuada nisi dui ac nisl. Donec dignissim venenatis facilisis. Pellentesque ac mi maximus, fermentum enim pharetra, rutrum justo. Vestibulum maximus sapien nec sapien egestas, sed dictum ex fringilla. Nam in nunc sapien. Aenean urna urna, pulvinar eget dolor eget, finibus posuere elit.', 5, 'Fantastic story', 9, 1, NULL),
(10, '2026-07-05T09:26:45.112Z', 'Praesent pulvinar pellentesque odio in tempor. Mauris sit amet neque turpis. Nulla laoreet tellus posuere velit tincidunt bibendum. Nullam blandit tortor sit amet posuere fringilla. Donec quis dolor sit amet arcu scelerisque viverra. Proin elementum tincidunt consectetur. Aenean eleifend tellus nunc, sed dapibus ex luctus in. Pellentesque rhoncus lectus magna, a ornare ex posuere at. Nunc nec nulla lacus. Vestibulum dapibus suscipit ex. Duis ac nulla at felis auctor sodales vitae nec nisl. Sed lacinia purus vel magna porttitor viverra. Vestibulum tincidunt lectus quis purus feugiat laoreet. Pellentesque porttitor at nulla non semper. Fusce sodales gravida dolor quis elementum. Curabitur sed libero eros.', 4, 'Very Intruiging story', 10, 1, NULL),
(11, '2026-07-05T09:31:35.582Z', 'Praesent pulvinar pellentesque odio in tempor. Mauris sit amet neque turpis. Nulla laoreet tellus posuere velit tincidunt bibendum. Nullam blandit tortor sit amet posuere fringilla. Donec quis dolor sit amet arcu scelerisque viverra. Proin elementum tincidunt consectetur. Aenean eleifend tellus nunc, sed dapibus ex luctus in. Pellentesque rhoncus lectus magna, a ornare ex posuere at. Nunc nec nulla lacus. Vestibulum dapibus suscipit ex. Duis ac nulla at felis auctor sodales vitae nec nisl. Sed lacinia purus vel magna porttitor viverra. Vestibulum tincidunt lectus quis purus feugiat laoreet. Pellentesque porttitor at nulla non semper. Fusce sodales gravida dolor quis elementum. Curabitur sed libero eros.', 1, '1 star', 11, 1, NULL),
(12, '2026-07-05T09:32:49.648Z', 'Nunc et dictum massa. Proin euismod elit et sodales iaculis. Etiam tristique libero eu maximus tincidunt. Integer congue elementum nibh, non mollis eros finibus a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec leo auctor ipsum scelerisque egestas et vitae mauris. Suspendisse potenti. Curabitur quis lorem nec ex malesuada scelerisque. Donec in nunc dui. Suspendisse potenti. Etiam in eleifend mauris.', 0, 'Could not get through it', 12, 1, NULL),
(13, '2026-07-05T09:33:30.730Z', 'Vivamus quis eleifend orci. Praesent sed purus commodo, feugiat quam quis, lacinia nisi. Integer hendrerit ipsum vitae arcu gravida vestibulum. Duis elementum at eros nec auctor. Donec vestibulum tellus quis tortor ultrices elementum. Morbi posuere quam consectetur, rhoncus leo sed, consequat purus. Mauris eu gravida felis. Nunc at ultricies risus, in ultrices ex. Nullam lorem lacus, sodales a mollis id, faucibus ac erat. Aliquam lacinia metus vel mattis auctor. Pellentesque vel hendrerit nunc. Ut malesuada felis ligula, et sagittis urna hendrerit sit amet. Vestibulum in imperdiet ipsum. Ut egestas porta risus eget tincidunt.', 1, 'Not much to say', 13, 1, NULL),
(14, '2026-07-05T09:34:07.408Z', 'Morbi in velit et libero pulvinar blandit. Nulla tempor sem quis orci malesuada molestie. Fusce ante sapien, consequat eu aliquam placerat, elementum at elit. Quisque non ante eget tortor pellentesque lobortis. Mauris vel magna eu sem auctor consectetur dictum eget nulla. Donec tempor metus sapien, nec faucibus neque luctus sit amet. Praesent sed augue mi. Vivamus ac pellentesque nunc. Pellentesque dictum maximus libero sit amet varius. Aliquam aliquet consectetur mi, vitae interdum nisi pharetra ut. Cras tempor sapien vel feugiat gravida. Donec ornare diam eget euismod vulputate. Nunc pretium hendrerit mi vitae porttitor. Donec vitae mi quis lacus semper ullamcorper. Morbi sagittis massa nec pulvinar finibus.', 3, 'Very average', 14, 1, NULL),
(15, '2026-07-05T09:34:46.567Z', 'Praesent pulvinar pellentesque odio in tempor. Mauris sit amet neque turpis. Nulla laoreet tellus posuere velit tincidunt bibendum. Nullam blandit tortor sit amet posuere fringilla. Donec quis dolor sit amet arcu scelerisque viverra. Proin elementum tincidunt consectetur. Aenean eleifend tellus nunc, sed dapibus ex luctus in. Pellentesque rhoncus lectus magna, a ornare ex posuere at. Nunc nec nulla lacus. Vestibulum dapibus suscipit ex. Duis ac nulla at felis auctor sodales vitae nec nisl. Sed lacinia purus vel magna porttitor viverra. Vestibulum tincidunt lectus quis purus feugiat laoreet. Pellentesque porttitor at nulla non semper. Fusce sodales gravida dolor quis elementum. Curabitur sed libero eros.', 4, 'Fantastic start to this series', 15, 1, NULL),
(16, '2026-07-05T09:35:53.326Z', 'Praesent pulvinar pellentesque odio in tempor. Mauris sit amet neque turpis. Nulla laoreet tellus posuere velit tincidunt bibendum. Nullam blandit tortor sit amet posuere fringilla. Donec quis dolor sit amet arcu scelerisque viverra. Proin elementum tincidunt consectetur. Aenean eleifend tellus nunc, sed dapibus ex luctus in. Pellentesque rhoncus lectus magna, a ornare ex posuere at. Nunc nec nulla lacus.', 3, 'Liked it', 16, 1, NULL),
(17, '2026-07-05T09:38:37.075Z', 'Integer dignissim imperdiet porta. Morbi venenatis vulputate justo, sit amet ultrices turpis mattis vitae. Donec ultrices tempor erat, non lobortis turpis ultricies ut. Donec convallis diam in mi lobortis, id egestas ligula aliquet. Nam nunc risus, ullamcorper ac gravida at, convallis egestas lacus. Maecenas pharetra, neque sed rutrum ultricies, est enim volutpat turpis, faucibus aliquet risus ex a est. Aenean vulputate dui nulla, nec sagittis felis luctus nec.', 0, 'Pretty boring', 17, 1, NULL),
(18, '2026-07-05T09:41:06.846Z', 'Praesent pulvinar pellentesque odio in tempor. Mauris sit amet neque turpis. Nulla laoreet tellus posuere velit tincidunt bibendum. Nullam blandit tortor sit amet posuere fringilla. Donec quis dolor sit amet arcu scelerisque viverra. Proin elementum tincidunt consectetur. Aenean eleifend tellus nunc, sed dapibus ex luctus in. Pellentesque rhoncus lectus magna, a ornare ex posuere at. Nunc nec nulla lacus. Vestibulum dapibus suscipit ex. Duis ac nulla at felis auctor sodales vitae nec nisl. Sed lacinia purus vel magna porttitor viverra. Vestibulum tincidunt lectus quis purus feugiat laoreet. Pellentesque porttitor at nulla non semper. Fusce sodales gravida dolor quis elementum. Curabitur sed libero eros.', 3, 'Classics', 18, 1, NULL),
(19, '2026-07-05T09:43:23.722Z', 'Nam ornare, magna ut suscipit accumsan, tortor turpis fringilla leo, non vehicula ante enim vel elit. Morbi ut felis lobortis, tincidunt arcu a, hendrerit nisi. Praesent pulvinar pellentesque odio in tempor. Mauris sit amet neque turpis. Nulla laoreet tellus posuere velit tincidunt bibendum. Nullam blandit tortor sit amet posuere fringilla. Donec quis dolor sit amet arcu scelerisque viverra. Proin elementum tincidunt consectetur.', 4, 'I liked the ending a lot', 19, 1, NULL),
(20, '2026-07-05T09:44:51.740Z', 'Nunc et dictum massa. Proin euismod elit et sodales iaculis. Etiam tristique libero eu maximus tincidunt. Integer congue elementum nibh, non mollis eros finibus a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec leo auctor ipsum scelerisque egestas et vitae mauris. Suspendisse potenti. Curabitur quis lorem nec ex malesuada scelerisque. Donec in nunc dui. Suspendisse potenti. Etiam in eleifend mauris. Morbi in velit et libero pulvinar blandit. Nulla tempor sem quis orci malesuada molestie. Fusce ante sapien, consequat eu aliquam placerat, elementum at elit.', 3, 'Very angst inducing', 20, 1, NULL);